export const SHIPPER_OPTIONS = [
  `HONGHAO CHEMICAL CO., LTD.
COMPREHENSIVE BUILDING,NO.13 CHUANGXIN
ROAD,JIANGGU FINE CHEMICAL INDUSTRIAL
AREA,JIANGGU,SIHUI,GUANGDONG,CHINA
TEL:0086-758-3267663 FAX:0086-758-3115313`,
  `GUANGZHOU MINHAO NEW MATERIAL CO. LTD.
ROOM 202,NO.12 SHIHU SHISI ROAD,DAYUAN STREET,
BAIYUN DISTRICT,GUANGZHOU,GUANGDONG,CHINA.`,
]

export const SHIPPER_LABELS = [
  'HONGHAO CHEMICAL CO., LTD.',
  'GUANGZHOU MINHAO NEW MATERIAL CO. LTD.',
]
